workflow:
  rules:
    # Allow running a pipeline on version branches (not tags!)
    - if: $CI_COMMIT_BRANCH =~ "/^v/"
      
variables:
  DEBIAN_FRONTEND: "noninteractive"
  DEVELOPER: "1"
  RUST_BACKTRACE: "1"
  RUST_VERSION: "1.60"
  
build:
  image: ubuntu:20.04
  script: >-
    apt-get update -qq
    apt-get install -qqy \
      autoconf \
      build-essential \
      git \
      libgmp-dev \
      libpq-dev \
      libsqlite3-dev \
      libtool \
      python3 \
      python3-pip \
      openssh-client \
      curl \
      clang \
      libssl-dev \
      wget \
      libssl-dev \
      pkg-config \
      gettext \
      zlib1g-dev
    rm -rf /var/lib/apt/lists/*

    pip install -U sh wheel pip poetry

    if [ -f "pyproject.toml" ]; then
      poetry export --without-hashes > requirements.txt
    fi

    pip install -U -r requirements.txt
    
    curl \
      --proto '=https' \
      --tlsv1.2 \
      -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain ${RUST_VERSION}
      
    ~/.cargo/bin/rustup toolchain install ${RUST_VERSION} \
      --component rustfmt --allow-downgrade

    python3 build.py
      
  artifacts:
    paths:
      - lightningd-{$CI_COMMIT_BRANCH}.tar.bz2
