.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-ADDGOSSIP" "7" "" "Core Lightning 22.11rc1" ""
.SH NAME
lightning-addgossip -- Command for injecting a gossip message (low-level)
.SH SYNOPSIS
\fBaddgossip\fR \fImessage\fR
.SH DESCRIPTION
The \fBaddgossip\fR RPC command injects a hex-encoded gossip message into
the gossip daemon.  It may return an error if it is malformed, or may
update its internal state using the gossip message.
.PP
Note that currently some paths will still silently reject the gossip: it
is best effort.
.PP
This is particularly used by plugins which may receive channel_update
messages within error replies.
.SH RETURN VALUE
On success, an empty object is returned.
.SH AUTHOR
Rusty Russell <\fIrusty@rustcorp.com.au\fR> is mainly responsible.
.SH SEE ALSO
lightning-pay(7)
.SH RESOURCES
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
\" SHA256STAMP:c4122741702cf08faac182bcbe267ad6b46243e25737cf87cab7ec27832ad5fd
