.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-LISTFORWARDS" "7" "" "Core Lightning 22.11rc1" ""
.SH NAME
lightning-listforwards -- Command showing all htlcs and their information
.SH SYNOPSIS
\fBlistforwards\fR [\fIstatus\fR] [\fIin_channel\fR] [\fIout_channel\fR]
.SH DESCRIPTION
The \fBlistforwards\fR RPC command displays all htlcs that have been
attempted to be forwarded by the Core Lightning node.
.PP
If \fIstatus\fR is specified, then only the forwards with the given status are returned.
\fIstatus\fR can be either \fIoffered\fR or \fIsettled\fR or \fIfailed\fR or \fIlocal_failed\fR
.PP
If \fIin_channel\fR or \fIout_channel\fR is specified, then only the matching forwards
on the given in/out channel are returned.
.SH RETURN VALUE
On success, an object containing \fBforwards\fR is returned.  It is an array of objects, where each object contains:
.IP "\(bu" 2
\fBin_channel\fR (short_channel_id): the channel that received the HTLC
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBin_msat\fR (msat): the value of the incoming HTLC
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBstatus\fR (string): still ongoing, completed, failed locally, or failed after forwarding (one of \(dqoffered\(dq, \(dqsettled\(dq, \(dqlocal_failed\(dq, \(dqfailed\(dq)
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBreceived_time\fR (number): the UNIX timestamp when this was received
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBin_htlc_id\fR (u64, optional): the unique HTLC id the sender gave this (not present if incoming channel was closed before ugprade to v22.11)
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBout_channel\fR (short_channel_id, optional): the channel that the HTLC (trying to) forward to
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBout_htlc_id\fR (u64, optional): the unique HTLC id we gave this when sending (may be missing even if out_channel is present, for old forwards before v22.11)
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBstyle\fR (string, optional): Either a legacy onion format or a modern tlv format (one of \(dqlegacy\(dq, \(dqtlv\(dq)
.LP
If \fBout_msat\fR is present:
.IP "\(bu" 2
\fBfee_msat\fR (msat): the amount this paid in fees
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBout_msat\fR (msat): the amount we sent out the \fIout_channel\fR
.LP
If \fBstatus\fR is \(dqsettled\(dq or \(dqfailed\(dq:
.IP "\(bu" 2
\fBresolved_time\fR (number): the UNIX timestamp when this was resolved
.LP
If \fBstatus\fR is \(dqlocal_failed\(dq or \(dqfailed\(dq:
.IP "\(bu" 2
\fBfailcode\fR (u32, optional): the numeric onion code returned
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBfailreason\fR (string, optional): the name of the onion code returned
.SH AUTHOR
Rene Pickhardt <\fIr.pickhardt@gmail.com\fR> is mainly responsible.
.SH SEE ALSO
lightning-autoclean-status(7), lightning-getinfo(7)
.SH RESOURCES
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
\" SHA256STAMP:6dcb8a95254886ed601ab630388418638e59c550349135fc28934b00ffd37b1f
