.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-DELEXPIREDINVOICE" "7" "" "Core Lightning 22.11rc1" ""
.SH NAME
lightning-delexpiredinvoice -- Command for removing expired invoices
.SH SYNOPSIS
\fBdelexpiredinvoice\fR [\fImaxexpirytime\fR]
.SH DESCRIPTION
The \fBdelexpiredinvoice\fR RPC command removes all invoices that have
expired on or before the given \fImaxexpirytime\fR.
.PP
If \fImaxexpirytime\fR is not specified then all expired invoices are
deleted.
.SH RETURN VALUE
On success, an empty object is returned.
.SH AUTHOR
ZmnSCPxj <\fIZmnSCPxj@protonmail.com\fR> is mainly responsible.
.SH SEE ALSO
lightning-delinvoice(7), lightning-autoclean-status(7)
.SH RESOURCES
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
\" SHA256STAMP:1ef5a35d1263ab8b9a94ad91d6559c720c79e64547e90c8dcbd84fdd3d282417
