.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-UNRESERVEINPUTS" "7" "" "Core Lightning 22.11rc1" ""
.SH NAME
lightning-unreserveinputs -- Release reserved UTXOs
.SH SYNOPSIS
\fBunreserveinputs\fR \fIpsbt\fR [\fIreserve\fR]
.SH DESCRIPTION
The \fBunreserveinputs\fR RPC command releases (or reduces reservation)
on UTXOs which were previously marked as reserved, generally by
lightning-reserveinputs(7).
.PP
The inputs to unreserve are the inputs specified in the passed-in \fIpsbt\fR.
.PP
If \fIreserve\fR is specified, it is the number of blocks to decrease
reservation by; default is 72.
.SH RETURN VALUE
On success, an object containing \fBreservations\fR is returned.  It is an array of objects, where each object contains:
.IP "\(bu" 2
\fBtxid\fR (txid): the transaction id
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBvout\fR (u32): the output number which was reserved
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBwas_reserved\fR (boolean): whether the input was already reserved (usually \fCtrue\fR)
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBreserved\fR (boolean): whether the input is now reserved (may still be \fCtrue\fR if it was reserved for a long time)
.LP
If \fBreserved\fR is \fItrue\fR:
.IP "\(bu" 2
\fBreserved_to_block\fR (u32): what blockheight the reservation will expire
.LP
On failure, an error is reported and no UTXOs are unreserved.
.PP
The following error codes may occur:
- -32602: Invalid parameter, i.e. an unparseable PSBT.
.SH AUTHOR
niftynei <\fIniftynei@gmail.com\fR> is mainly responsible.
.SH SEE ALSO
lightning-unreserveinputs(7), lightning-signpsbt(7), lightning-sendpsbt(7)
.SH RESOURCES
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
\" SHA256STAMP:b9cbd68e13388c6b92d11f24cbd0850e273718f6725ea30c82b6989985e5c23b
