.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-WAITBLOCKHEIGHT" "7" "" "Core Lightning 22.11rc1" ""
.SH NAME
lightning-waitblockheight -- Command for waiting for blocks on the blockchain
.SH SYNOPSIS
\fBwaitblockheight\fR \fIblockheight\fR [\fItimeout\fR]
.SH DESCRIPTION
The \fBwaitblockheight\fR RPC command waits until the blockchain
has reached the specified \fIblockheight\fR.
It will only wait up to \fItimeout\fR seconds (default 60).
.PP
If the \fIblockheight\fR is a present or past block height, then this
command returns immediately.
.SH RETURN VALUE
On success, an object is returned, containing:
.IP "\(bu" 2
\fBblockheight\fR (u32): The current block height (>= \fIblockheight\fR parameter)
.LP
If \fItimeout\fR seconds is reached without the specified blockheight
being reached, this command will fail with a code of \fC2000\fR.
.SH AUTHOR
ZmnSCPxj <\fIZmnSCPxj@protonmail.com\fR> is mainly responsible.
.SH RESOURCES
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
\" SHA256STAMP:4f2012cbad4b109593a32852bad6e34fe2d23eed5d9d08bccb574356cda7d4cd
