.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-TXSEND" "7" "" "Core Lightning 22.11rc1" ""
.SH NAME
lightning-txsend -- Command to sign and send transaction from txprepare
.SH SYNOPSIS
\fBtxsend\fR \fItxid\fR
.SH DESCRIPTION
The \fBtxsend\fR RPC command signs and broadcasts a transaction created by
\fBtxprepare\fR.
.SH RETURN VALUE
On success, an object is returned, containing:
.IP "\(bu" 2
\fBpsbt\fR (string): the completed PSBT representing the signed transaction
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBtx\fR (hex): the fully signed transaction
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBtxid\fR (txid): the transaction id of \fItx\fR
.LP
On failure, an error is reported (from bitcoind), and the inputs from
the transaction are unreserved.
.PP
The following error codes may occur:
- -1: Catchall nonspecific error.
.SH AUTHOR
Rusty Russell <\fIrusty@rustcorp.com.au\fR> is mainly responsible.
.SH SEE ALSO
lightning-txprepare(7), lightning-txdiscard(7)
.SH RESOURCES
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
\" SHA256STAMP:9f66da74019446e2f006f1f67d5755a5ba97b0d4b79a1e1bd29644fa4f1af9b1
