.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-DISCONNECT" "7" "" "Core Lightning 22.11rc1" ""
.SH NAME
lightning-disconnect -- Command for disconnecting from another lightning node
.SH SYNOPSIS
\fBdisconnect\fR \fIid\fR [\fIforce\fR]
.SH DESCRIPTION
The disconnect RPC command closes an existing connection to a peer,
identified by \fIid\fR, in the Lightning Network, as long as it doesn't have
an active channel. If \fIforce\fR is set then it will disconnect even with
an active channel.
.PP
The \fIid\fR can be discovered in the output of the listpeers command, which
returns a set of peers:
.LP
.EX
{
     \(dqpeers\(dq: [
          {
               \(dqid\(dq: \(dq0563aea81...\(dq,
               \(dqconnected\(dq: true,
               ...
          }
     ]
}
.EE
.PP
Passing the \fIid\fR attribute of a peer to \fIdisconnect\fR will terminate the
connection.
.SH RETURN VALUE
On success, an empty object is returned.
.PP
On error the returned object will contain \fCcode\fR and \fCmessage\fR properties,
with \fCcode\fR being one of the following:
.IP "\(bu" 2
-32602: If the given parameters are wrong.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
-1: Catchall nonspecific error.
.SH AUTHOR
Michael Hawkins <\fImichael.hawkins@protonmail.com\fR>.
.SH SEE ALSO
lightning-connect(1), lightning-listpeers(1)
.SH RESOURCES
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
\" SHA256STAMP:125a33b5ea5ae1b9e1c586698f8e62a4ef1200271c593e4e243486caa12454aa
