.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-EMERGENCYRECOVER" "7" "" "Core Lightning 22.11rc1" ""
.SH NAME
lightning-emergencyrecover -- Command for recovering channels from the emergency.recovery file in the lightning directory
.SH SYNOPSIS
\fBemergencyrecover\fR
.SH DESCRIPTION
The \fBemergencyrecover\fR RPC command fetches data from the emergency.recover
file and tries to reconnect to the peer and force him to close the channel.
The data in this file has enough information to reconnect and sweep the funds.
.PP
This recovery method is not spontaneous and it depends on the peer, so it should
be used as a last resort to recover the funds stored in a channel in case of severe
data loss.
.SH RETURN VALUE
On success, an object is returned, containing:
- \fBstubs\fR (array of hexs):
- Each item is the channel ID of the channel successfully inserted
.SH AUTHOR
Aditya <\fIaditya.sharma20111@gmail.com\fR> is mainly responsible.
.SH SEE ALSO
lightning-getsharedsecret(7)
.SH RESOURCES
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
\" SHA256STAMP:74a5d801d5926e11d196040b69846339f3ea2c8992dcde9c1159caf97c4a73c5
